version: '3.8'

services:
  db:
    container_name: sayman_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: sayman-db
    ports:
      - "5432:5432"
    volumes:
      - sayman-data:/var/lib/postgresql/data/
volumes:
  sayman-data:
